 
SELECT * FROM PERSON 
SELECT * FROM DEPARTMENT

--1. Combine information from Person and Department table using cross join or Cartesian product.
SELECT * FROM PERSON P
CROSS JOIN
DEPARTMENT

--2. Find all persons with their department name 
SELECT P.PERSONNAME , D.DEPARTMENTNAME
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID


--3. Find all persons with their department name & code.  
SELECT P.PERSONNAME , D.DEPARTMENTNAME , D.DEPARTMENTCODE
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID


--4. Find all persons with their department code and location. 
SELECT P.PERSONNAME ,D.DEPARTMENTCODE ,D.LOCATION
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID


--5. Find the detail of the person who belongs to Mechanical department. 
SELECT * FROM PERSON P
INNER JOIN DEPARTMENT D 
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE DEPARTMENTNAME='MECHANICAL'


--6. Final person’s name, department code and salary who lives in Ahmedabad city. 
SELECT P.PERSONNAME ,D.DEPARTMENTCODE,P.SALARY
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE CITY='AHMEDABAD'


--7. Find the person's name whose department is in C-Block. 
SELECT P.PERSONNAME ,D.LOCATION
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE LOCATION='C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 
SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME 
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE CITY='JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 
SELECT * FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE DEPARTMENTNAME='CIVIL' AND JOININGDATE >'2001-08-01'

--10. Display all the person's name with the department whose joining date difference with the current date is more than 25 years. 
SELECT P.PERSONNAME ,D.DEPARTMENTNAME
FROM PERSON P
LEFT JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE DATEDIFF(YEAR,JOININGDATE,GETDATE())>25

--11. Find department wise person counts. 
SELECT D.DEPARTMENTNAME, COUNT(P.PERSONID) AS NO_OF_PER FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME


--12. Give department wise maximum & minimum salary with department name. 
SELECT D.DEPARTMENTNAME,MAX(SALARY) AS MAX_SAL,MIN(SALARY) AS MIN_SAL
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME

--13. Find city wise total, average, maximum and minimum salary. 
SELECT P.CITY ,SUM(SALARY) AS TOTAL_SAL ,AVG(SALARY) AS AVG_SAL , MAX(SALARY) AS MAX_SAL , MIN(SALARY) AS MIN_SAL
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY P.CITY


--14. Find the average salary of a person who belongs to Ahmedabad city. 
SELECT P.CITY,AVG(SALARY) AS AVG_SAL 
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE CITY='AHMEDABAD'
GROUP BY P.CITY

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. 
SELECT CONCAT(P.PERSONNAME,'       LIVES IN      ',P.CITY,'       WORKS IN     ',D.DEPARTMENTNAME)
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID

--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly.
SELECT CONCAT(P.PERSONNAME,'   EARNS    ',P.SALARY,'   FROM   ',D.DEPARTMENTNAME,'  MONTHLY  ')
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID


--17. Find city & department wise total, average & maximum salaries. 
SELECT P.CITY,D.DEPARTMENTNAME , SUM(SALARY) AS TOTAL_SAL , MAX(SALARY) AS MAX_SAL, AVG(SALARY) AS AVG_SAL
FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY P.CITY ,D.DEPARTMENTNAME


--18. Find all persons who do not belong to any department. 
SELECT P.PERSONNAME ,D.DEPARTMENTNAME FROM PERSON  P
LEFT JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE DEPARTMENTNAME IS NULL


--19. Find all departments whose total salary is exceeding 100000. 
SELECT D.DEPARTMENTNAME,SUM(SALARY) FROM PERSON P
INNER JOIN DEPARTMENT D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING P.SALARY>100000
ORDER BY SUM(SALARY)

--20. List all departments who have no person. 
SELECT DepartmentName
FROM DEPARTMENT
LEFT JOIN PERSON
ON DEPARTMENT.DepartmentID = PERSON.DepartmentID
WHERE PERSON.DepartmentID IS NULL;

SELECT * FROM DEPARTMENT
SELECT * FROM PERSON


--21. List out department names in which more than two persons are working. 
SELECT DEPARTMENT.DepartmentName,
       COUNT(PERSON.PERSONID) AS No_Of_Employees
FROM DEPARTMENT
JOIN PERSON
ON DEPARTMENT.DepartmentID = PERSON.DepartmentID
GROUP BY DEPARTMENT.DepartmentID, DEPARTMENT.DepartmentName
HAVING COUNT(PERSON.PERSONID) > 2;

--22. Give a 10% increment in the computer department employee’s salary. (Use Update)
UPDATE PERSON
SET Salary = Salary + (Salary * 0.10)
WHERE DepartmentID IN (
    SELECT DepartmentID
    FROM DEPARTMENT
    WHERE DepartmentName = 'Computer'
);